import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const interFont = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Board',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${interFont.className} antialiased`}>
      <body className="bg-navy-950 text-navy-50 antialiased">{children}</body>
    </html>
  )
}
